name: DBML playground build

on:
  pull_request:
    branches:
      [ "master" ]
    paths:
      - packages/playground/**/*

env:
  NODE_VERSION: 16.x
  WORK_DIR: packages/playground/
  PARSER_DIR: packages/parser/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Build parser
        working-directory: ${{ env.PARSER_DIR }}
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build
      - name: Build playground
        working-directory: ${{ env.WORK_DIR }}
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build
      